version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clientservicedbb
    ports:
      - "3308:3306"

  backend:
    build:
      context: ./car-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientservicedbb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=123456 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

#  frontend:
#    build:
#      context: ./smartHome-front
#    ports:
#      - "80:80"
#    depends_on:
#      - backend